#!/bin/bash

# Get Volume
get_volume() {
  volume=`amixer get $1 | tail -n1 | awk -F ' ' '{print $5}' | tr -d '[%]'`
  echo "$volume"
}

# Set Volume
set_volume() {
	amixer -q set $1 $2%
}

# Toggle Volume
toggle_vol() {
	status=`amixer get $1 | tail -n1 | grep -wo 'on'`

	if [[ "$status" == "on" ]]; then
		amixer set $1 toggle
	else
		amixer set $1 toggle
	fi
}

# Get Volume Icon
get_icon() {
	status=`amixer get $1 | tail -n1 | grep -wo 'on'`

  if [[ "$1" == "Master" ]]; then
    if [[ "$status" == "on" ]]; then
      echo "墳"
    else
      echo "ﱝ"
    fi
  elif [[ "$1" == "Capture" ]]; then
    if [[ "$status" == "on" ]]; then
      echo ""
    else
      echo ""
    fi
  fi
}


# Execute accordingly
if [[ "$1" == "--set-vol" ]]; then
	set_volume "Master" "$2"
elif [[ "$1" == "--toggle-vol" ]]; then
	toggle_vol "Master"
elif [[ "$1" == "--set-mic" ]]; then
	set_volume "Capture" "$2"
elif [[ "$1" == "--toggle-mic" ]]; then
	toggle_vol "Capture"
fi

while true; do
  if [[ "$1" == "--get-vol" ]]; then
    get_volume "Master"
  elif [[ "$1" == "--get-vol-icon" ]]; then
    get_icon "Master"
  elif [[ "$1" == "--get-mic" ]]; then
    get_volume "Capture"
  elif [[ "$1" == "--get-mic-icon" ]]; then
    get_icon "Capture"
  fi
  sleep 3
done
