#!/usr/bin/env bash

icons=("\uEDBC" "\uEBD9" "\uEBE0" "\uEBDD" "\uEBE2" "\uEBD4" "\uEBD2" "\uE1A4")

geticon() {
	level=$(awk -v n="$CAPACITY" 'BEGIN{print int(n/12) - 1}')
	if [ "$STATE" = "Charging" ]; then
		echo "\uE1A3"
	else
		echo "${icons[$level]}"
	fi
}

status() {
	if [ "$STATE" = "Charging" ]; then
		echo -n "charging"

		if [ "$RATE" -gt 0 ]; then
			echo ", $(gettime) left"
		else
			echo ""
		fi
	elif [ "$STATE" = "Discharging" ]; then
		echo "$(gettime)h left"
	else
		echo "fully charged"
	fi
}

color() {
	if [ "$CAPACITY" -le 20 ]; then
		echo '#f38ba8'
	else
		echo '#a6e3a1'
	fi
}

wattage() {
	R=$(($(cat /sys/class/power_supply/BAT0/current_now) * $(cat /sys/class/power_supply/BAT0/voltage_now)))
	echo "$(bc -l <<<"scale=1; $R / 1000000000000") W"
}

gettime() {
	FULL=$(cat /sys/class/power_supply/BAT0/charge_full)
	NOW=$(cat /sys/class/power_supply/BAT0/charge_now)

	if [ "$RATE" -gt 0 ]; then
		if [ "$STATE" = "Discharging" ]; then
			EX="$NOW / $RATE"
		else
			EX="($FULL - $NOW) / $RATE"
		fi
		date -u -d@"$(bc -l <<<"$EX * 3600")" +%H:%M
	fi
}

while true; do
	RATE=$(cat /sys/class/power_supply/BAT0/current_now)
	CAPACITY=$(cat /sys/class/power_supply/BAT0/capacity)
	STATE=$(cat /sys/class/power_supply/BAT0/status)

	echo '{ "icon": "'"$(geticon)"'", "percentage": '"$CAPACITY"', "wattage": "'"$(wattage)"'", "status": "'"$(status)"'", "color": "'"$(color)"'" }'
	sleep 3
done
