#!/bin/sh

status=$(nmcli g | grep -oE "disconnected")
essid=$(nmcli -t -f active,ssid dev wifi | grep '^yes' | cut -d: -f2)

if [ $status ] ; then
    icon="睊"
    text=""
else
    icon=""
fi
text="${essid}"


while true; do
  case $1 in
    --essid) echo $text;;
    --icon) echo $icon;;
  esac
  sleep 10
done

