#!/bin/bash

## Files and cmd
EWW="eww -c $HOME/.config/eww/"
focusmon=$(hyprctl monitors -j | jq -r '.[] | select(.focused == true) | .id')

## Run eww daemon if not running already
if [[ ! $(pidof eww) ]]; then
    ${EWW} daemon
    sleep 1
fi

hyprctl dispatch focusmonitor "$focusmon"

## Open sidebar
## ${EWW} open "sidebar$focusmon"

## Open standard widgets and bar
NB_MONITORS=($(hyprctl monitors -j | jq -r '.[] | .id'))
for id in "${NB_MONITORS[@]}"; do
    # make top bar for every display
    bar="bar$id"
    hyprctl dispatch focusmonitor "$id"
    ${EWW} open "$bar"
done
