#!/usr/bin/bash

scripts=$HOME/.config/hypr/scripts

# notification daemon
dunst &

waybar &

# screenlock when idle
$scripts/idle_handler &

# auth agent
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# wallpaper
wallpapers=(~/Pictures/Wallpapers/*)
swww init &

gtk-launch discord &
# gtk-launch slack &
