#!/usr/bin/bash

scripts=$HOME/.config/hypr/scripts

# notification daemon
dunst &

# screenlock when idle
$scripts/idle_handler &

# KDE auth
/usr/lib/polkit-kde-authentication-agent-1 &

/usr/bin/prime-run /usr/bin/discord --enable-features=UseOzonePlatform --ozone-platform=wayland
/usr/bin/prime-run /usr/bin/slack --enable-features=UseOzonePlatform --ozone-platform=wayland
