#!/usr/bin/bash

scripts=$HOME/.config/hypr/scripts

# notification daemon
dunst &

# screenlock when idle
$scripts/idle_handler &

# auth agent
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# wallpaper
sleep 1 && swww init && swww img $HOME/Pictures/Wallpapers/1.png

gtk-launch discord &
gtk-launch slack &
