syntax enable
set hidden
set nowrap
set fileencoding=utf-8
set pumheight=10
set cmdheight=2
set iskeyword+=-
set mouse=a
set splitbelow
set splitright
set conceallevel=0
set tabstop=4 softtabstop=4
set shiftwidth=4
set smarttab
set expandtab
set autoindent
set number
set relativenumber
set incsearch
set nohlsearch
set noshowmode
set nobackup
set nowritebackup
set noswapfile
set undodir=~/.config/nvim/undodir
set updatetime=50
set timeoutlen=300
set formatoptions-=cro
