syntax enable
set hidden
set nowrap
set encoding=utf-8
set fileencoding=utf-8
set pumheight=10
set cmdheight=2
set iskeyword+=-
set mouse=a
set splitbelow
set splitright
set tabstop=4 softtabstop=4
set shiftwidth=4
set smarttab
set expandtab
set autoindent
set number
set relativenumber
set incsearch
set nohlsearch
set noshowmode
set nobackup
set noswapfile
set undodir=~/.config/nvim/undodir
set undofile
set scrolloff=8
set updatetime=300
set timeoutlen=300
set formatoptions-=cro
